# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Codersstop
tagline:          Where coders stop for solutions
url:              http://codersstop.github.io
paginate:         1
baseurl:          /
author:
  name:           Awesome Coders
  url:            https://twitter.com/codersstop
  email:          codersstopofficial@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/codersstop
